local opt, api = vim.opt, vim.api
vim.env.NVIM_TUI_ENABLE_TRUE_COLOR = 1
opt.termguicolors = true
opt.ttyfast = true
opt.cursorline = true
opt.wrap = false
opt.number = true
opt.relativenumber = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.softtabstop = 2
opt.expandtab = true
opt.smarttab = true
opt.autoindent = true
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.ttimeoutlen = 0
opt.timeout = false
opt.showmode = false
opt.virtualedit = 'block'
opt.conceallevel = 0
opt.showtabline = 1
opt.laststatus = 3
opt.signcolumn = 'yes'
opt.breakindent = true
opt.spelloptions = 'camel'
opt.foldmethod = 'indent'
opt.foldlevel = 99
opt.winwidth = 25
opt.pumheight = 15
opt.list = true
opt.listchars = 'tab:»·,nbsp:+,trail:·,extends:→,precedes:←'
opt.completeopt = "menu,menuone,noselect,popup"
opt.fillchars = {
  stl = ' ',
  stlnc = '-',
  msgsep = ' ',
  foldopen = '',
  foldclose = '',
  fold = ' ',
  foldsep = ' ',
  diff = '╱',
  eob = ' ',
}
opt.cmdheight = 0
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.colorcolumn = '0'
opt.undofile = true
opt.updatetime = 100
opt.redrawtime = 1500
